version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Chicago"
    versioning-strategy: increase
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
    commit-message:
      prefix: "build"
      include: "scope"
    allow:
      - dependency-type: "production"
        update-type: "version-update:semver-minor"
      - dependency-type: "development"
        update-type: "version-update:semver-minor"
